### ISSUE TITLE
Color is lost when the text in the TextComponent goes to a second line

### ISSUE THREAD

**Issue by DoNotSpamPls** [KyoriPowered/text#19]
When trying to color a full message wrapped in a TextComponent, if that message happens to be too long and happens to go to the second line in the chat, the color is lost. This does not happen with the legacy serializer, which is the current workaround.

For example, this code will break it:
`TextComponent.builder("This message is an example of a bug with KyoriPowered/Text. It is too long, so it goes to a second line, and unfortunately it loses its color :/").color(TextColor.RED).build()`

Related: VelocityPowered/Velocity#91

**Comment by kashike** [comment]
This isn't an issue with text.

Here's the JSON for a component created through text:
```json
{
  "text": "This message is an example of a bug with KyoriPowered/Text. It is too long, so it goes to a second line, and unfortunately it loses its color :/",
  "color": "red"
}
```
and here's the JSON for a component created using vanilla:
```json
{
  "color": "red",
  "text": "This message is an example of a bug with KyoriPowered/Text. It is too long, so it goes to a second line, and unfortunately it loses its color :/"
}
```

**Comment by lucko** [comment]
The 'white text after line break' issue usually occurs when legacy formatting codes are used inside the "text" component instead of using the `color` attribute.

**Comment by DoNotSpamPls** [comment]
Yes, after more research I've found that this issue isn't present in the raw TextComponent builder, but rather in the LegacyChatColorUtils translate method. I'm sincerely sorry for reporting an issue incorrectly.
