### ISSUE TITLE
Allow heritage on TextComponent and Builder TextComponent 

### ISSUE THREAD

**Issue by MissIlys** [KyoriPowered/text#24]
Hey,

I using this api on my project but i have a translation system. I want implement this system in this api on my project. It's possible to allow heritage on TextComponent and Builder TextComponent?

Best regards,
MissIlys

**Comment by kashike** [comment]
Sorry, I don't quite understand what you mean?

**Comment by MissIlys** [comment]
I have a translatable system in my server, and when i want translate a text, i have a parameters(array of object) and string(the key). I want to create a super type of TextComponent for add the parameters and when i send message, i translate the content with parameters depending on the player.

**Comment by lucko** [comment]
You should extend from `AbstractBuildableComponent` instead :)
