### ISSUE TITLE
Trailing colors not applied after TextComponent append

### ISSUE THREAD

**Issue by Crypnotic** [KyoriPowered/text#32]
I've got a TextComponent defined as a prefix which is applied to all messages. At the end of the prefix, there is a color code to be applied. Prefix: &7[&bPrefix&7] &a

The messages are then loaded as TextComponent objects.

Once ready to send, I append the message TextComponent to the prefix TextComponent.

The expected behavior is that the entirety of the message, until another code is found, should be green since the prefix has a trailing &a color code; however, the message appears white until another color code is found.

Example: http://prntscr.com/nkpxhj

**Comment by kashike** [comment]
Could you provide the code you're using, please?

**Comment by Crypnotic** [comment]
Velocity version: 1.0.0-SNAPSHOT (Latest)
Text version: 1.12-1.6.5 (Packaged with Velocity)

Specific code chunks: https://pastebin.com/DULhHL7J

Appending in code: https://github.com/Crypnotic/Neutron/blob/refactor/announcement/src/main/java/me/crypnotic/neutron/module/announcement/Announcement.java#L65

Color method for serializing: https://github.com/Crypnotic/Neutron/blob/refactor/announcement/src/main/java/me/crypnotic/neutron/util/StringHelper.java#L37-L44

TypeSerializer that is used to load from config:  https://github.com/Crypnotic/Neutron/blob/refactor/announcement/src/main/java/me/crypnotic/neutron/api/serializer/TextComponentSerializer.java

**Comment by Crypnotic** [comment]
Text values used in the screenshot

Prefix text: `&7[&bPrefix&7] &a`

Message text: `This entire messages should be &agreen`

**Comment by kashike** [comment]
This is actually how this is intended to work:
```java
color("&7[&bPrefix&7] &a").append(color("This entire messages should be &agreen"))
```

```json
{
  "text": "",
  "extra": [
    {
      "text": "[",
      "color": "gray"
    },
    {
      "text": "Prefix",
      "color": "aqua"
    },
    {
      "text": "] ",
      "color": "gray"
    },
    {
      "text": "",
      "color": "green"
    },
    {
      "text": "This entire messages should be ",
      "extra": [
        {
          "text": "green",
          "color": "green"
        }
      ]
    }
  ]
}
```

The "prefix" is part of one root, and the root doesn't have any style - the last child, which has empty `content`, is styled with green.

**Comment by Crypnotic** [comment]
So you're saying this is working as intended? That's strange since the same string appended beforehand would yield the proper result

**Comment by kashike** [comment]
Yes, it is working as intended -- if you look at the above JSON you'll see that the second-last object has empty (`""`) text and `green` colouring - this is your last `&a` in the prefix. To continue with that formatting, you'd need to be appending to the last child component, not the root component itself.

**Comment by Crypnotic** [comment]
Component children are immutable. When appending onto a child component, would it return the child component or the root component?

**Comment by kashike** [comment]
It would return the child component.
___
This is one of the reasons that use of the legacy serialiser is discouraged, in favour of the JSON serialiser (or custom ones - YAML, XML, etc).

**Comment by Crypnotic** [comment]
So there is essentially no way to apply a prefix with a trailing color code to a TextComponent without creating multiple new components just to get there?

**Comment by Crypnotic** [comment]
Side note: I would use JSON, but I can't expect most people to take the time to create a proper JSON message just to send announcements. That's just opening an avenue to get littered with issues that are user error

**Comment by kashike** [comment]
You can deserialise all as one (`color(prefix + message)`) to create a component, otherwise you'll have to do a dance.

**Comment by Crypnotic** [comment]
Which means if I want to support JSON messages also, I would have to serialize, deserialize into legacy, append, reserialize. Either direction requires a dance

**Comment by kashike** [comment]
Assuming the last bit of the prefix defines the colour for the text coming up, yes, you'd need to do a dance still:
```java
    final Component prefix = color("&7[&bPrefix&7] &a");
    final List<Component> prefixChildren = prefix.children();
    final Style prefixLastChildStyle = prefixChildren.get(prefixChildren.size() - 1).style();
    final Component message = color("This entire messages should be &agreen");
    final Component result = prefix.append(TextComponent.builder().style(prefixLastChildStyle).append(message));
```
results in a component that serialises into the following JSON:
```json
{
  "text": "",
  "extra": [
    {
      "text": "[",
      "color": "gray"
    },
    {
      "text": "Prefix",
      "color": "aqua"
    },
    {
      "text": "] ",
      "color": "gray"
    },
    {
      "text": "",
      "color": "green"
    },
    {
      "text": "",
      "extra": [
        {
          "text": "This entire messages should be ",
          "extra": [
            {
              "text": "green",
              "color": "green"
            }
          ]
        }
      ],
      "color": "green"
    }
  ]
}
```
and into the following legacy text:
```
§7[§bPrefix§7] §aThis entire messages should be green
```
___
The above code is based on text 3.0.0 - if you're on a previous version you'll have to manually apply any colouring + decorations, as `Style` does not exist in previous versions.

**Comment by Crypnotic** [comment]
It's a good thing Velocity packages 1.6.5 🥇

**Comment by Crypnotic** [comment]
Solved for now I guess. In case anyone needs a method that works on versions < 3.0.0

[Neutron - StringHelper#append](https://github.com/Crypnotic/Neutron/blob/master/src/main/java/me/crypnotic/neutron/util/StringHelper.java#L70-L79)
