### ISSUE TITLE
Legacy serializer breaks MC detection of links in chat

### ISSUE THREAD

**Issue by Crypnotic** [KyoriPowered/text#33]
When serializing a message from legacy that includes a link and sending it to a player. The link is not clickable.

The same link sent in base MC chat is clickable, but legacy seems to break this function

**Comment by kashike** [comment]
Code?

**Comment by Crypnotic** [comment]
All legacy serialization passes through this method.

https://github.com/Crypnotic/Neutron/blob/master/src/main/java/me/crypnotic/neutron/util/StringHelper.java#L40-L46

**Comment by astei** [comment]
With #34 merged in, you can simply use `LegacyComponentSerializer.legacyLinking()` instead. I think it's safe to close this bug.
