### ISSUE TITLE
**Suggestion** make formatByLegacyChar(Char char) public

### ISSUE THREAD

**Issue by Narimm** [KyoriPowered/text#35]
I might have missed where it's possible but I was wondering if the 
`AbstractLegacyComponentSerializer.formatByLegacyChar(Char char) method could be made public ?

Why? I would like to be able to store a List<TextFormat> against a series of regex's to allow dynamic colourization by keyword.  Historically we did this with ChatColor 
so we would start with a config file 
`/badmin/b > c` 
we take the regex create a pattern `/badmin/b` and then take  `c` and get the ChatColor that it corresponds to.  we store them in a map and use it to dynamically format chat.

We can use the c to create a TextComponent that contains the textFormat but not ideal as when we later need to apply it to other text its cumbersome.

**Comment by lucko** [comment]
`AbstractLegacyComponentSerializer` is not a public class.

https://github.com/KyoriPowered/text/blob/b93d45c1e4563139919bea5f6152d0bacc9d5717/serializer-legacy/src/main/java/net/kyori/text/serializer/legacy/AbstractLegacyComponentSerializer.java#L40

If you need a custom implementation of the serializer, I suggest copying the code you need & implementing your own. :)

**Comment by Narimm** [comment]
sorry I hadnt looked I had assumed making that public would have enabled a enduser to do something like
`TextFormat format = LegacyComponentSerializer.INSTANCE.formatByLegacyChar('c');`

**Comment by Narimm** [comment]
and I have worked around the issue by creating a Enum that pairs legacy chars to TextFormats

**Comment by lucko** [comment]
👍
