### ISSUE TITLE
TextComponent.joinWith

### ISSUE THREAD

**Issue by ItsDoot** [KyoriPowered/text#45]
It would be nice if there was an additional static method on `TextComponent`, like Sponge's `Text.joinWith`:

- `static TextComponent joinWith(TextComponent separator, Iterable<TextComponent> components)`
- `static TextComponent joinWith(TextComponent separator, TextComponent... components)`

**Comment by kashike** [comment]
https://github.com/KyoriPowered/text/commit/becceb39a87347480b225bbb2890a3171ca259b0
