### ISSUE TITLE
Add suggestion of shading to readme

### ISSUE THREAD

**Issue by Andre601** [KyoriPowered/text#61]
When you install multiple plugins, which use the Text library and multiple of them doesn't shade/relocate the lib itself, can the following warnings on Spigot appear:
```
[05:37:18] [Server thread/WARN]: [:plugin] Loaded class net.kyori.text.Component from :plugin which is not a depend, softdepend or loadbefore of this plugin.
```

I suggest adding a note, or code example to the readme, to inform about this step being recommended, if not even required.

**Comment by kashike** [comment]
I am not going to start recommend something just because Spigot-Bukkit is trying to make something sound scary by sending a `WARN`-level log message.

**Comment by Andre601** [comment]
Understandable, however, this "`WARN`-level log message" as you put it will basically make the plugin unusable in the future, just because of this (And because Spigot pulling a MD_5 again I suppose).

What is wrong about suggesting to shade the dependency into your plugin by relocating it? I can't see anything wrong with this and it would prevent and solve more issues than it may cause at all.

**Comment by kashike** [comment]
I will not be *recommending* something like this just because of what one platform is doing - the instructions to relocate something differ from buildsystem to buildsystem, and I do not want to clutter the README with buildsystem instructions. Any competent developer can easily figure out how to relocate text if necessary.

**Comment by MiniDigger** [comment]
a simple "To avoid version conflicts its suggested to relocated this lib when shading" tho tbh thats what you should do with every lib soooo

**Comment by Andre601** [comment]
> a simple "To avoid version conflicts its suggested to relocated this lib when shading" tho tbh thats what you should do with every lib soooo

A bit late to respond to this (Mainly because I had other concerns and basically forgot this until now) but by your general logic should every project ever shade in libraries, no? Does that mean they should also shade in (and relocate) the entirety of the SpigotMC API?

I do get your actual point, but for starters, which surprise, surprise still exist in 2021, is shading libs and wrappers into a project not a too well-known process and not as common as you think.

Otherwise, we would by your logic not have people, that still complain in the JDA Discord, that their bot isn't starting and that they get something like a "NoClassDefException"... Because then they would know, that they need to shade JDA into their project.

Yes, for more experienced people is this probably a common thing to do, but we should stop expecting people to already know the stuff required here, because thanks to YouTube and people getting into programming more and more early, will you also encounter people that may not have the experience, or people like me who learn better by doing, than reading.
Constantly assuming people to have the knowledge and giving responses that makes it look like *they* are at fault because it was *sooooo obvious* that this should be done will only drive away people from this.

Anyway, that is all I wanted to say here... Do with it what you want, I don't care that much, but I just wanted to give my points here, now that I found this issue again...

**Comment by kezz** [comment]
I would welcome a PR to the docs that includes a line mentioning that shading should be done when using the platform builds. However, the README in this repo is not the correct place for that.
