### ISSUE TITLE
TextComponent.join() is functioning wrong?

### ISSUE THREAD

**Issue by StealWonders** [KyoriPowered/text#63]
I just got version 3.0.4 of text to try and use the TextComponent.join() function. 
This method either has a bug or is functioning wrong in my eyes as when you only have 1 TextComponent it tries to join it with nothing as can be seen in the image.

![javaw_lPmyXoU6I8](https://user-images.githubusercontent.com/6114858/79669277-b8a5df80-81ba-11ea-9d52-9488e323cdf9.png)

The code used for executing the command can be found here: https://gist.github.com/StealWonders/96027959ddc0120c7cfcd3c806a30ccd
The output of line 15 is " 1 ".

If you need any further information, feedback or testing from me feel free to ask.

**Comment by kashike** [comment]
I am not able to reproduce.
```java
    final List<Component> l1 = new ArrayList<>();
    l1.add(TextComponent.of("foo"));
    final Component c1 = TextComponent.join(TextComponent.of("OHNOES"), l1);
    assertEquals(TextComponent.builder().append(r1).build(), c1);
    System.out.println(c1);
```
output:
```
TextComponentImpl{content="", children=[TextComponentImpl{content="foo", children=[], style=Style{color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}}
```
